PRIMARY_COLOR = "#1E293B"
ACCENT_COLOR = "#334155"
ACTION_COLOR = "#2563EB"

SHIFT_MAP = {
    "`": "~",
    "1": "!",
    "2": "@",
    "3": "#",
    "4": "$",
    "5": "%",
    "6": "^",
    "7": "&",
    "8": "*",
    "9": "(",
    "0": ")",
    "-": "_",
    "=": "+",
    "[": "{",
    "]": "}",
    "\\": "|",
    ";": ":",
    ",": "<",
    ".": ">",
    "/": "?",
}

FN_MAP = {
    "`": "esc",
    "1": "f1",
    "2": "f2",
    "3": "f3",
    "4": "f4",
    "5": "f5",
    "6": "f6",
    "7": "f7",
    "8": "f8",
    "9": "f9",
    "0": "f10",
    "-": "f11",
    "=": "f12",
}

KEYBOARD_ROWS = [
    [
        ("`", "`"),
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
        ("6", "6"),
        ("7", "7"),
        ("8", "8"),
        ("9", "9"),
        ("0", "0"),
        ("-", "-"),
        ("=", "="),
        ("⌫", "backspace", 75, ACCENT_COLOR),
    ],
    [
        ("Tab", "tab", 65, ACCENT_COLOR),
        ("Q", "q"),
        ("W", "w"),
        ("E", "e"),
        ("R", "r"),
        ("T", "t"),
        ("Y", "y"),
        ("U", "u"),
        ("I", "i"),
        ("O", "o"),
        ("P", "p"),
        ("[", "["),
        ("]", "]"),
        ("\\", "\\"),
    ],
    [
        ("Caps", "caps lock", 75, ACCENT_COLOR),
        ("A", "a"),
        ("S", "s"),
        ("D", "d"),
        ("F", "f"),
        ("G", "g"),
        ("H", "h"),
        ("J", "j"),
        ("K", "k"),
        ("L", "l"),
        (";", ";"),
        ("Enter", "enter", 85, ACTION_COLOR),
    ],
    [
        ("Shift", "shift", 95, ACCENT_COLOR),
        ("Z", "z"),
        ("X", "x"),
        ("C", "c"),
        ("V", "v"),
        ("B", "b"),
        ("N", "n"),
        ("M", "m"),
        (",", ","),
        (".", "."),
        ("/", "/"),
        ("Shift", "right shift", 95, ACCENT_COLOR),
    ],
    [
        ("Ctrl", "ctrl", 65, ACCENT_COLOR),
        ("win", "left windows", 65, ACCENT_COLOR),
        ("alt", "alt", 65, ACCENT_COLOR),
        ("Space", "space", 209, ACTION_COLOR),
        ("alt", "right alt", 65, ACCENT_COLOR),
        ("Fn", "Fn", 65, ACCENT_COLOR),
        ("←", "left", 50, ACCENT_COLOR),
        ("↑", "up", 50, ACCENT_COLOR),
        ("↓", "down", 50, ACCENT_COLOR),
        ("→", "right", 50, ACCENT_COLOR),
    ],
]